[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = '2072/PHP-Indenting-for-VIm'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo = 'Yggdroot/LeaderF'
build =  './install.sh'
hook_add = '''
    nnoremap <silent><unique> <Leader>Ft :<C-U>LeaderfBufTagAll<CR>
    nnoremap <silent><unique> <Leader>Ff :<C-U>Leaderf file --no-ignore<CR>
    nnoremap <silent><unique> <Leader>Fn :<C-U>LeaderfFunction<CR>
    nnoremap <silent><unique> <Leader>Fb :<C-U>LeaderfBufferAll<CR>
    nnoremap <silent><unique> <Leader>Fh :<C-U>LeaderfHelp<CR>
'''

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'alvan/vim-php-manual'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'jeffkreeftmeijer/vim-numbertoggle'

[[plugins]]
repo = 'ludovicchabant/vim-gutentags'
if = 'executable("ctags") || executable("universal-ctags")'

[[plugins]]
repo = 'joonty/vdebug'

[[plugins]]
repo = 'haginaga/vim-compiler-phpunit'

[[plugins]]
repo = 'janko-m/vim-test'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'michaeljsmith/vim-indent-object'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
repo = 'rayburgemeestre/phpfolding.vim'

[[plugins]]
repo = 'skywind3000/asyncrun.vim'

[[plugins]]
repo = 'shawncplus/phpcomplete.vim'

[[plugins]]
repo = 'vim-scripts/wombat256.vim'

[[plugins]]
repo = 'vimwiki/vimwiki'

[[plugins]]
repo = 'vim-scripts/EasyMotion'

[[plugins]]
repo = 'vim-scripts/Efficient-python-folding'

[[plugins]]
repo = 'vim-scripts/argtextobj.vim'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-cucumber'

[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-git'

[[plugins]]
repo = 'tpope/vim-projectionist'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-rhubarb'

[[plugins]]
repo = 'tpope/vim-scriptease'

[[plugins]]
repo = 'tpope/vim-sensible'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-unimpaired'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'garbas/vim-snipmate'

[[plugins]]
repo = 'MarcWeber/vim-addon-mw-utils'

[[plugins]]
repo = 'tomtom/tlib_vim'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'mhinz/vim-signify'

[[plugins]]
repo = 'dense-analysis/ale'

[[plugins]]
repo = 'neoclide/coc.nvim'
build = 'yarn install --frozen-lockfile'
if = 'executable("node")'
hook_add = '''
    autocmd FileType php nnoremap <silent> <Leader>gd <Plug>(coc-definition)
    autocmd FileType php nnoremap <silent> <Leader>gi <Plug>(coc-implementation)
    autocmd FileType php nnoremap <silent> <Leader>gr <Plug>(coc-references)
    autocmd FileType php nnoremap <silent> <Leader>gr <Plug>(coc-references)
    autocmd FileType php nnoremap <silent> <Leader>gr <Plug>(coc-references)
    autocmd FileType php nnoremap <silent> ]d <Plug>(coc-diagnostic-next)
    autocmd FileType php nnoremap <silent> [d <Plug>(coc-diagnostic-prev)
    autocmd FileType php setl formatexpr=CocAction('formatSelected')

    command! -nargs=0 CocFormat :call CocAction('format')
    command! -nargs=0 CocRename :call CocAction('rename')
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_post_update = ':UpdateRemotePlugins'

[[plugins]]
repo = 'roxma/nvim-yarp'
on_if = '!has("nvim")'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_if = '!has("nvim")'
