"

if &compatible
  set nocompatible               " Be iMproved
endif

execute 'source ' . expand('~/.vim/rc/dein.rc.vim')

filetype plugin indent on
syntax enable

set t_Co=256
set number relativenumber
set encoding=utf-8
set fileencoding=utf-8
set fileencodings=utf-8,big5,gb2312,sjis
set hlsearch
set modeline
set background=dark
set suffixes=.bak,~,.swp,.o,.info,.aux,.log,.dvi,.bbl,.blg,.brf,.cb,.ind,.idx,.ilg,.inx,.out,.toc
set noshowmode
set updatetime=300
set shortmess+=c

colorscheme wombat256mod

let g:coc_global_extensions = ['coc-phpls', 'coc-json', 'coc-snippets', 'coc-tsserver', 'coc-tslint', 'coc-eslint']

" autocomplete
augroup MyCustomFileType
  autocmd FileType css setl omnifunc=csscomplete
  autocmd FileType perl setl sw=4 ts=4 et
  autocmd FileType c setl sw=4 ts=4 et
  autocmd BufNewFile,BufRead *.go setl filetype=go sw=4 ts=4
  autocmd BufNewFile,BufRead *.mako setl filetype=mako
  autocmd BufNewFile,BufRead *.gradle setl filetype=groovy sw=4 ts=4 et
  autocmd BufNewFile,BufRead *.thrift if &ft == 'conf' | setl filetype=thrift
  autocmd BufNewFile,BufRead *.md setl filetype=markdown
augroup end

map th :tabprev<CR>
map tl :tabnext<CR>
nnoremap <silent> <F12> :TlistToggle<CR>

let NERDTreeIgnore=['\~$', '\.lo$', '\.la$', '\.pyc']
let NERDTreeMinimalUI=1

let Tlist_Use_Right_Window = 1
let os = substitute(system('uname'), '\n', '', '')
if os ==# 'FreeBSD'
	let Tlist_Ctags_Cmd = '/usr/local/bin/exctags'
endif

let g:changelog_username = 'Gasol Wu <gasol.wu@gmail.com>'

if filereadable($HOME.'/.vimrc_local')
	source $HOME/.vimrc_local
endif
let g:vdebug_options = {
\ 'port': 9003,
\ 'ide_key': 'gasolwu',
\ 'proxy_host': '',
\ 'proxy_port': 0,
\ }

comm! W exec 'w !sudo tee % > /dev/null' | e!

if executable('universal-ctags')
	let g:gutentags_ctags_executable = 'universal-ctags'
	let g:Lf_Ctags = 'universal-ctags'
endif

set tags=./.tags;,.tags
let g:gutentags_ctags_tagfile='.ctags'
let s:vim_tags = expand('~/.cache/tags')
let g:gutentags_cache_dir = s:vim_tags
let g:asyncrun_open = 8
let g:ale_virtualtext_cursor = 1
set statusline+=%{gutentags#statusline()}

let g:projectionist_heuristics = {
\   'tests/&phpunit.xml|phpunit.xml.dist': {
\     'src/*.php': {
\       'alternate': 'tests/{}Test.php',
\       'type': 'source'
\     },
\     'tests/*Test.php': {
\       'alternate': 'src/{}.php',
\       'type': 'test'
\     }
\   }
\ }

function! CocCurrentFunction()
    return get(b:, 'coc_current_function', '')
endfunction

let g:lightline = {
\  'colorscheme': 'wombat',
\  'active': {
\    'left': [ [ 'mode', 'paste' ],
\              [ 'cocstatus', 'currentfunction', 'readonly', 'filename', 'modified' ] ]
\  },
\  'component_function': {
\    'cocstatus': 'coc#status',
\    'currentfunction': 'CocCurrentFunction'
\  }
\}

nmap <silent> t<C-n> :TestNearest<CR>
nmap <silent> t<C-f> :TestFile<CR>
nmap <silent> t<C-s> :TestSuite<CR>
nmap <silent> t<C-l> :TestLast<CR>
nmap <silent> t<C-g> :TestVisit<CR>
