"

if &compatible
  set nocompatible               " Be iMproved
endif

execute 'source ' . expand('~/.vim/rc/dein.rc.vim')

filetype plugin indent on
syntax enable

set t_Co=256
set number relativenumber
set encoding=utf-8
set fileencoding=utf-8
set fileencodings=utf-8,big5,gb2312,sjis
set hlsearch
set modeline
set background=dark
set suffixes=.bak,~,.swp,.o,.info,.aux,.log,.dvi,.bbl,.blg,.brf,.cb,.ind,.idx,.ilg,.inx,.out,.toc
set noshowmode
set updatetime=300
set shortmess+=c
if has('termguicolors')
  set termguicolors
endif
if !has('nvim') && $TERM ==# 'screen-256color'
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
endif

colorscheme wombat256mod

augroup MyCustomFileType
  autocmd FileType css setl omnifunc=csscomplete
  autocmd FileType perl setl sw=4 ts=4 et
  autocmd FileType c setl sw=4 ts=4 et
  autocmd BufNewFile,BufRead *.go setl filetype=go sw=4 ts=4
  autocmd BufNewFile,BufRead *.mako setl filetype=mako
  autocmd BufNewFile,BufRead *.gradle setl filetype=groovy sw=4 ts=4 et
  autocmd BufNewFile,BufRead *.thrift if &ft == 'conf' | setl filetype=thrift
  autocmd BufNewFile,BufRead *.md setl filetype=markdown
augroup end

let g:changelog_username = 'Gasol Wu <gasol.wu@gmail.com>'

if filereadable($HOME.'/.vimrc_local')
	source $HOME/.vimrc_local
endif

comm! W exec 'w !sudo tee % > /dev/null' | e!
