"

if &compatible
  set nocompatible               " Be iMproved
endif

let g:NERDTreeHijackNetrw=0
let mapleader=" "
execute 'source ' . expand('<sfile>:p:h') . '/dein.rc.vim'
if !has('nvim')
  autocmd VimEnter * call dein#call_hook('post_source')
endif

filetype plugin indent on
syntax enable
nnoremap <SPACE> <NOP>
nnoremap Q <NOP>

set t_Co=256
set guifont=Menlo-Regular:h14
set number relativenumber
set encoding=utf-8
set fileencoding=utf-8
set fileencodings=utf-8,big5,gb2312,sjis
set hlsearch
set modeline
set background=dark
set suffixes=.bak,~,.swp,.o,.info,.aux,.log,.dvi,.bbl,.blg,.brf,.cb,.ind,.idx,.ilg,.inx,.out,.toc
set noshowmode
set updatetime=300
set shortmess+=c
set scrolloff=4
if has('termguicolors')
  set termguicolors
endif
if !has('nvim') && $TERM ==# 'tmux-256color'
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
endif

try
  colorscheme wombat256mod
catch /^Vim\%((\a\+)\)\=:E185/
endtry

augroup MyCustomFileType
  autocmd FileType css setl omnifunc=csscomplete
  autocmd FileType perl setl sw=4 ts=4 et
  autocmd FileType c setl sw=4 ts=4 et
  autocmd FileType git set foldmethod=syntax
  autocmd BufNewFile,BufRead *.go setl filetype=go sw=4 ts=4
  autocmd BufNewFile,BufRead *.mako setl filetype=mako
  autocmd BufNewFile,BufRead *.gradle setl filetype=groovy sw=4 ts=4 et
  autocmd BufNewFile,BufRead *.thrift if &ft == 'conf' | setl filetype=thrift
  autocmd BufNewFile,BufRead *.md setl filetype=markdown
augroup end

let g:changelog_username = 'Gasol Wu <gasol.wu@gmail.com>'

if has('nvim')
  set pumblend=15
  lua << EOF
    require('mylspconfig')
    local loaded, treesitter = pcall(require, 'nvim-treesitter.configs')
    if loaded then
      treesitter.setup {
        ensure_installed = { "c", "lua", "php", "phpdoc", "dart", "javascript", "typescript", "vim", "vue", "yaml", "ruby", "rust", "query", "python", "scss", "css", "html" },
        auto_install = true,
        highlight = {
          enable = true,
          use_languagetree = true,
        },
        indent = {
          enable = true
        },
        playground = {
          enable = true,
          disable = {},
          updatetime = 25, -- Debounced time for highlighting nodes in the playground from source code
          persist_queries = false, -- Whether the query persists across vim sessions
          keybindings = {
            toggle_query_editor = 'o',
            toggle_hl_groups = 'i',
            toggle_injected_languages = 't',
            toggle_anonymous_nodes = 'a',
            toggle_language_display = 'I',
            focus_language = 'f',
            unfocus_language = 'F',
            update = 'R',
            goto_node = '<cr>',
            show_help = '?',
          },
        },
      }
    end
EOF
endif
