name: CI
on: [push, pull_request]

jobs:
  setup:
    name: Run setup
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        neovim: [true, false]
        version: [stable, nightly]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          version: ${{ matrix.version }}
          neovim: ${{ matrix.neovim }}
      - name: Initialize
        env:
          EDITOR: ${{ steps.vim.outputs.executable }}
        run: $EDITOR -es -n -u ./vimrc  +'redir! >> /dev/stdout | messages | redir END | q!'
